### PR TITLE
Fix: wrapper.js & adapt-contrib-spoor updated to work with Jest testing. (fixes #284)

### LINKED ISSUE #284: Update spoor extension to work with jest testing
### Subject of the issue/enhancement/features
- Using import the dependency at the top of the file instead of require
- Return early in spoor's wrapper.js if Adapt.course does not exist

https://github.com/adaptlearning/adapt_framework/pull/3383

### PR DESCRIPTION
**Pull request by joe-allen-89**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)
#284 

Linked to Jest testing (https://github.com/adaptlearning/adapt_framework/pull/3383)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)
### Fix
* Return early added to wrapper.js if Adapt.course does not exist
* jquery.keycombo changed from require to import

### CODE REVIEW

**Review by ethan-lp — APPROVED** [review]

File: js/adapt-contrib-spoor.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ import StatefulSession from './adapt-stateful-session';
 import OfflineStorage from './adapt-offlineStorage-scorm';
 import offlineStorage from 'core/js/offlineStorage';
 import { shouldStart as shouldStartCookieLMS, start as startCookieLMS } from './scorm/cookieLMS';
+import { onKeyCombo } from './../libraries/jquery.keycombo';
```
Comment (oliverfoster) [inline js/adapt-contrib-spoor.js:7]:
```suggestion
import './../libraries/jquery.keycombo';
```
